spring.application.name=the_cheaper

spring.datasource.url=jdbc:mysql://localhost:3306/the_cheaper?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.path=/api-docs

# life token
jwt.secret=4933a3915f7f2b1c4e9d0a68735b2e3f84c5a9b7d8e2f1c4a5b6c7d8e9f0a1b2
jwt.expiration=3600000
jwt.refresh-expiration=86400000

# Mail (Mailtrap)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6b72e98e1b37ba
spring.mail.password=****0e81
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP expiration
app.otp.expiration-minutes=15